### ISSUE TITLE
App installs connects and creates child devices correctly.. it works as expected except it causes boot loops

### ISSUE THREAD

**Issue by kamakazie2** [dbochicchio/vera-OpenSprinkler#1]
Hi. Thank you for the plugin. I am on VeraPlus running the Opensprinkler app. It installed correctly. I put in my md5 password and ip address. It crerated all the zones, humidity , and schedule. However it constantly reboots vera every ~40 seconds.

If I remove the app the rebooting stops. If I reinstall is comes back.

running firmware 1.7.5186 (7.31)

**Comment by dbochicchio** [comment]
Hi. are you running the latest version via GitHub or via the store?

**Comment by kamakazie2** [comment]
Hi

Thank you for the quick reply!

I installed it from the store. Is the code on git newer?

**Comment by kamakazie2** [comment]
i installed from GIT code and it works 100% and no boot loop. thank you!

**Comment by dbochicchio** [comment]
Thanks for reporting. I've updated the store version as well. I forgot to do because the store was experiencing some problems back in August.

**Comment by kamakazie2** [comment]
My pleasure.. and thanks again for the great plugin!
